server:
  hostname: localhost
  port: 3000
  communication_timeout: 1
hardware:
  port: COM12
  communication_timeout: 1
fan_profiles:
  50% PWM:
    type: pwm
    values:
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    name: 50% PWM
  100% PWM:
    type: pwm
    values:
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    name: 100% PWM
  1000 RPM:
    type: rpm
    values:
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    name: 1000 RPM
  Test:
    type: RPM
    values:
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    name: Test
  Test2:
    type: PWM
    values:
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
    - 50
fan_aliases:
  0: 'Fan #1'
  1: 'Fan #2'
  2: 'Fan #3'
  3: 'Fan #4'
  4: 'Fan #5'
  5: 'Fan #6'
  6: 'Fan #7'
  7: 'Fan #8'
  8: 'Fan #9'
  9: 'Fan #10'
